AWSTemplateFormatVersion: 2010-09-09
Description: Template Cloud Formation
Parameters:
  Environment:
    Type: String
    Description: Stack environment
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  webserver:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroupIds:
        - !Ref sgwebserver
      InstanceType: t2.small
      ImageId: ami-fe408091
      Tags:
        - Key: Environment
          Value: !Ref Environment
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update && apt install -y apache2

  sgwebserver:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow port 80
      SecurityGroupIngress:
        CidrIp: 0.0.0.0/0
        FromPort: 80
        ToPort: 80
        IpProtocol: tcp
